apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: fcg-apps
  labels:
    app: payments-api
stringData:
  # Placeholders for sensitive configuration values
  # Database connection string 
  ConnectionStrings__DefaultConnection: "Server=sqlserver-service;Database=PaymentsDb;User Id=sa;Password=YOUR_PASSWORD;TrustServerCertificate=True;Encrypt=False;"
  # RabbitMQ credentials
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"
  # Payment Webhook API key
  PaymentSettings__WebhookApiKey: "your-256-bit-secret"